format = '$username$hostname$shlvl$kubernetes$directory$git_branch$git_commit$git_state$hg_branch$docker_context$package$cmake$dart$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$ruby$rust$swift$terraform$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$cmd_duration$line_break$lua$jobs$battery$time$status$character '

command_timeout="900"
add_newline = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[line_break]
disabled = false

[cmd_duration]
format = '[](#191E27)[( $duration)]($style bold)[](#191E27) '
style = 'red bg:#191E27'

[username]
format = '[$user]($style)[@]($style dimmed)'
style_user = 'cyan bold'

[hostname]
format = '[$hostname]($style) in '
style = 'cyan'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'white bold'
read_only = ' '
read_only_style = 'bold red'
truncation_length = 2
truncate_to_repo = true
disabled = false

[directory.substitutions]
'~/Projects/third-party' = ' third-party'
'~/Projects/work' = '華work'
'~/Projects/personal' = ' personal'
'~/Projects/aeroster' = ' aeroster'
'~/Projects' = 'ﮛ Projects'
'/Volumes/T7' = 'T7'

[python]
format = '[](#191E27)[$symbol$pyenv_prefix$version]($style bold)[(/$virtualenv)]($style dimmed)[](#191E27) '
style = 'yellow bg:#191E27'
python_binary = 'python'
symbol = ' '
disabled = false

[terraform]
format = '[](#191E27)[$symbol$version]($style)[](#191E27) '
version_format = '$raw'
style = 'purple bg:#191E27'
symbol = 'ﯟ '
disabled = false

[gcloud]
format = '[](#191E27)[$symbol$active]($style bold)[(/$region)]($style dimmed)[](#191E27) '
style = '#0F9D58 bg:#191E27'
symbol = ' '
disabled = false

[gcloud.region_aliases]
australia-southeast1 = 'au'
asia-northeast1 = 'asia-ne1'
us-central1 = 'u-c1'
us-east1 = 'us-e1'
us-east4 = 'us-e4'
us-west1 = 'us-w1'
us-west2 = 'us-w2'
us-west3 = 'us-w3'
us-west4 = 'us-w4'
europe-west1 = 'eu-w1'
europe-west2 = 'eu-w2'
europe-west3 = 'eu-w3'
europe-west4 = 'eu-w4'
europe-west6 = 'eu-w6'

[git_branch]
format = '[](#191E27)[$symbol$branch]($style)[](#191E27) '
style = 'yellow bg:#191E27'
symbol = ' '
only_attached = true
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
disabled = false

[nodejs]
symbol = ' '
disabled = true

[package]
symbol = ' '
disabled = true

[aws]
format = '[](#191E27)[$symbol$profile]($style bold)[(/$region)]($style dimmed)[](#191E27) '
style = 'red bg:#191E27'
symbol = ' '
disabled = false

[battery]
full_symbol = ''
charging_symbol = ''
discharging_symbol = ''

[dart]
symbol = ' '

[docker_context]
only_with_files = 'true'
symbol = ' '

[elixir]
symbol = ' '

[golang]
symbol = ' '

[hg_branch]
symbol = ''

[java]
symbol = ' '

[memory_usage]
symbol = ' '

[perl]
symbol = ' '

[php]
symbol = ' '

[ruby]
symbol = ' '

[rust]
format = '[](#191E27)[$symbol($version)]($style)[](#191E27) '
style = 'bold red bg:#191E27'
symbol = ' '

[swift]
symbol = 'ﯣ '
