format = ' $username$hostname$shlvl$kubernetes$directory$git_branch$git_commit$git_state$hg_branch$docker_context$package$cmake$dart$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$nim$nodejs$ocaml$perl$php$purescript$python$ruby$rust$swift$terraform$vagrant$zig$nix_shell$conda$memory_usage$aws$gcloud$openstack$env_var$crystal$custom$cmd_duration$line_break $lua$jobs$time$status$character'

command_timeout = "900"
add_newline = true

[character]
success_symbol = '[](green)'
error_symbol = '[](red)'

[line_break]
disabled = false

[cmd_duration]
format = ' [( $duration)]($style bold)'
style = 'red'

[username]
format = '[$user]($style)[@]($style dimmed)'
style_user = 'cyan bold'

[hostname]
format = '[$hostname]($style) in '
style = 'cyan'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'white bold'
read_only = ' '
read_only_style = 'bold red'
truncation_length = 2
truncate_to_repo = true
disabled = false

[directory.substitutions]
'/Volumes/T7' = 'T7'

[python]
format = ' [$symbol$pyenv_prefix$version]($style bold)[(/$virtualenv)]($style)'
style = 'yellow'
python_binary = 'python'
symbol = ''
disabled = false

[terraform]
format = ' [$symbol$version]($style)'
version_format = '$raw'
style = 'purple'
symbol = 'ﯟ'
disabled = false

[gcloud]
format = ' [$symbol]($style)[$active]($style bold)[(/$region)]($style)'
style = 'blue'
symbol = ''
disabled = false

[gcloud.region_aliases]
australia-southeast1 = 'au'
asia-northeast1 = 'as' # 'asia-ne1'
us-central1 = 'us' # 'us-c1'
us-east1 = 'us' # 'us-e1'
us-east4 = 'us' # 'us-e4'
us-west1 = 'us' # 'us-w1'
us-west2 = 'us' # 'us-w2'
us-west3 = 'us' # 'us-w3'
us-west4 = 'us' # 'us-w4'
europe-west1 = 'eu' # 'eu-w1'
europe-west2 = 'eu' # 'eu-w2'
europe-west3 = 'eu' # 'eu-w3'
europe-west4 = 'eu' # 'eu-w4'
europe-west6 = 'eu' # 'eu-w6'

[git_branch]
format = ' [$symbol$branch]($style)'
style = 'yellow'
symbol = ''
only_attached = true
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
disabled = false

[nodejs]
symbol = ''
disabled = true

[package]
symbol = ''
disabled = true

[aws]
format = ' [$symbol$profile]($style bold)[(/$region)]($style)'
style = 'red'
symbol = ' '
disabled = false

[battery]
disabled = true
full_symbol = ''
charging_symbol = ''
discharging_symbol = ''

[dart]
symbol = ''

[docker_context]
format = ' [$symbol$context]($style bold)'
only_with_files = 'true'
symbol = ''

[elixir]
symbol = ''

[golang]
format = ' [$symbol$version]($style)'
symbol = ''

[hg_branch]
symbol = ''

[java]
symbol = ' '

[memory_usage]
symbol = ''

[perl]
symbol = ''

[php]
symbol = ''

[ruby]
symbol = ''

[rust]
format = ' [$symbol$version]($style)'
style = 'bold red'
symbol = ''

[swift]
symbol = 'ﯣ'
